### ISSUE TITLE
For SEO shouldn't page.description be replaced by post.description?

### ISSUE THREAD

**Issue by deepanshu99** [nikhita/nikhita.github.io#2]

**Comment by nikhita** [comment]
Hi @deepanshu99, thanks for opening an issue!

IIRC `page.description` and `post.description` are inter-changeable. I wrote the SEO part long back so I am not sure and could be wrong. Can you elaborate a bit on the difference between them? :smile: 

From what I see [here](https://bl.ocks.org/roachhd/0991292c575536db96c5), it says that `post can be replaced with page or even site depending on your need`. 

Let me know more about this. Thanks!

**Comment by deepanshu99** [comment]
But the layout being used is post and post is using default as the layout. So wouldn't it be incorrect in this case to use `{{page.description}}` instead of `{{post.description}}` ?

**Comment by nikhita** [comment]
@deepanshu99 I see your point and it makes sense. But from what I have seen,

1. If anyone googles a post, it _does_ show the post's description, not the site's description. So this works.

2. From the link I had mentioned above, it _seems_ page and post are interchangeable in Jekyll. I am not really familiar with the internals of Jekyll to intelligibly comment if this is indeed true. 

Are you using a similar template for your website? What did you use for SEO on your site?

**Comment by deepanshu99** [comment]
I am using Lanyon Theme so I think everything should be almost the same. I am following the instructions posted on your blog. 

This is working flawlessly
```<meta name="description" content="{% if page.description %}{{ page.description }}{% else %}{{ site.description }}{% endif %}">
  {% if page.keywords %}
 <meta name="keywords" content="{{ page.keywords }}" />
  {% else %}
 <meta name="keywords" content="your-default-comma-separated-keywords" />
 {% endif %}
```

But `{{post.description}}` works only when an object is created.

```
  {%for post in site.posts%}
  <meta name="description" content="{% if post.description %}{{ post.description }}{% else %}{{ site.description }}{% endif %}">
  {% if post.keywords %}
 <meta name="keywords" content="{{ post.keywords }}" />
 {%endif%}
 {%endfor%}

```
 Any reason why the latter doesn't work the way the former works?

**Comment by nikhita** [comment]
@deepanshu99 Sorry for the late reply, got busy at work...

Sorry, I can't find a difference between the both of them. From what I see [here](https://bl.ocks.org/roachhd/0991292c575536db96c5), the problem should not exist so I am not sure why `{{post.description}}` works only when an object is created.

If you are still facing trouble with this, I would suggest you to create an issue on the https://github.com/jekyll/jekyll repo. :)

**Comment by nikhita** [comment]
Closing the issue due to age.
